CONFIG_ENV_CFLAGS   += \
    -Os -Wall -Werror \
    -g3 \
    -D_PLATFORM_IS_HOST_ \
    -DCONFIG_HTTP_AUTH_TIMEOUT=500 \
    -DCONFIG_MID_HTTP_TIMEOUT=500 \
    -DCONFIG_GUIDER_AUTH_TIMEOUT=500 \
    -DUSING_UTILS_JSON \
    -DIOTX_NET_INIT_WITH_PK_EXT \
    -DUSING_SHA1_IN_HMAC \
    -DCM_VIA_CLOUD_CONN \
    -DCM_VIA_CLOUD_CONN_MQTT

LDFLAGS             += -lpthread
