LIBA_TARGET := libiot_sdk.a

###############################################################################
# Compiler

CC := gcc
AR := ar

###############################################################################
# Path definitions

TOPDIR  := .
BLDDIR  := $(TOPDIR)/build
SRCDIR  := $(TOPDIR)/eng
HDRDIR  := $(shell find $(SRCDIR) -type d)

###############################################################################
# Application source files

SOURCE_FILES_C := $(shell find $(SRCDIR) -name *.c)

###############################################################################
# Standard application lib/header search paths

CFLAGS  := $(addprefix -I,$(HDRDIR))
LDFLAGS := -lpthread -lrt

###############################################################################
# Dependency rules

LIBOBJS := $(SOURCE_FILES_C:.c=.o)
LIBOBJS := $(subst $(SRCDIR),$(BLDDIR),$(LIBOBJS))

.PHONY: prepare all clean

all: prepare $(BLDDIR)/$(LIBA_TARGET)

prepare:
	-@mkdir -p $(BLDDIR)

$(BLDDIR)/$(LIBA_TARGET): $(LIBOBJS)
	@echo "Archiving $@ ..."
	@$(AR) -rcs $@ $^

$(BLDDIR)/%.o: $(SRCDIR)/%.c
	@echo "Compiling $< ..."
	@mkdir -p $(shell dirname $@)
	@$(CC) -o $@ -c $< $(CFLAGS)

clean:
	@rm -rf $(BLDDIR)
