LIBA_TARGET := libiot_sdk.a

###############################################################################
# Compiler

CC := gcc
AR := ar

###############################################################################
# Path definitions

TOPDIR  := .
BLDDIR  := build
SRCDIR  := eng
EXPDIR  := examples
HDRDIR  := $(shell find $(SRCDIR) -type d)

PROG_TARGET := $(shell ls $(EXPDIR) 2>/dev/null|grep example|sed 's:\.c::g;s:_:-:g')
PROG_TARGET := $(foreach V,$(PROG_TARGET),$(BLDDIR)/$(V))

###############################################################################
# Application source files

SOURCE_FILES_C := $(shell find $(SRCDIR) -name *.c)

###############################################################################
# Standard application lib/header search paths

CFLAGS  := $(addprefix -I,$(HDRDIR))
LDFLAGS := -L$(BLDDIR) -liot_sdk -lpthread -lrt

###############################################################################
# Dependency rules

LIBOBJS := $(SOURCE_FILES_C:.c=.o)
LIBOBJS := $(subst $(SRCDIR),$(BLDDIR),$(LIBOBJS))

.PHONY: prepare all clean prog

all: prepare $(BLDDIR)/$(LIBA_TARGET)

prog: all $(PROG_TARGET)

prepare:
	-@mkdir -p $(BLDDIR)

$(BLDDIR)/$(LIBA_TARGET): $(LIBOBJS)
	@echo "o Archiving $@ ..."
	@$(AR) -rcs $@ $^

$(PROG_TARGET): $(BLDDIR)/$(LIBA_TARGET)
	@echo "+ Linking $@ ..."
	@$(CC) -o $@ $(shell echo $@".c"|sed 's:$(BLDDIR):$(EXPDIR):g;s:-:_:g') $(CFLAGS) $(LDFLAGS)

$(BLDDIR)/%.o: $(SRCDIR)/%.c
	@echo ": Compiling $< ..."
	@mkdir -p $(shell dirname $@)
	@$(CC) -o $@ -c $< $(CFLAGS)

clean:
	@rm -rf $(BLDDIR)
